Ecommercepart2/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path

from app import views

urlpatterns = [
    path('', views.home,name='home'),
    path('home/', views.home,name='home'),
    path('login/',views.signin,name='login'),
    path('register/',views.register,name='register'),
    path('logout/',views.Signout,name='logout'),
    path('cartbox/',views.cartbox,name='cartbox'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('order/',views.order,name='order'),
    path('delete/<int:id>/', views.delete, name='delete'),
    # path('delete/<int:id>/', views.delete, name='delete'),
    
    path('edit/<int:id>/', views.edit, name='edit'),

]

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Customer(AbstractUser):
    address = models.CharField(max_length=255)
    contact_no = models.CharField(max_length=15)

    def __str__(self):
        return self.username  # Display the username in the admin site

class Product(models.Model):
    product_id = models.IntegerField()
    product_name = models.CharField(max_length=255)
    product_price = models.FloatField(default=0)
    product_image = models.ImageField(upload_to="images")

    def __str__(self):
        return self.product_name



class Cart(models.Model):
    user = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return f"{self.user.username}'s Cart - {self.product_id.product_name}"

class Order(models.Model):
    user = models.ForeignKey(Customer, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)  # Assuming Product is your product model
    # Other fields in your Order model

   
    def total_price(self):
        return self.cart.quantity * self.product.product_price if self.cart else 0

    def __str__(self):
        return f"{self.user.username}'s Order for {self.product.product_name}"

app/views.py
from django.shortcuts import get_object_or_404, render,redirect
from django.contrib.auth import logout,authenticate,login
from django.contrib.auth.models import User,AbstractUser
from django.contrib.auth import get_user_model
from django.urls import reverse
from app.models import Cart, Product,Customer,Order
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Sum



# Create your views here.
def home(request):
    products = Product.objects.all()
    context = {'products': products}
    return render(request, 'app/home.html', context)


@login_required(login_url="/login")
def add_to_cart(request, product_id):
    product = Product.objects.get(pk=product_id)

    if request.method == 'POST':
        quantity = int(request.POST.get('quantity', 1))
        user = request.user

        existing_cart_item = Cart.objects.filter(user=user, product_id=product).first()

        if existing_cart_item:
            existing_cart_item.quantity += quantity
            existing_cart_item.save()
        else:
            Cart.objects.create(user=user, product_id=product, quantity=quantity)

        # Calculate the total quantity of items in the cart
        total_quantity = Cart.objects.filter(user=user).aggregate(Sum('quantity'))['quantity__sum']

        # Update the session with the total quantity
        request.session['total_quantity'] = total_quantity

        return redirect('home')

    return render(request, 'app/home.html', {'product': product})


def signin(request):
    if request.method == 'GET':
        return render(request,'app/login.html')
    else:
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'You are now logged in.')
            next_url=request.GET.get('next')
            if next_url :
                return redirect(next_url)
            
            return redirect('home')
        else:
            messages.error(request, 'Invalid username or password.')
            return redirect('login')  
       
def register(request):
    if request.method == 'GET':
        return render(request, 'app/register.html')
    else:
        fn = request.POST['firstname']
        ln = request.POST['lastname']
        email = request.POST['email']
        username = request.POST['username']
        password = request.POST['password']

        User = get_user_model()

        # Use create_user method from the custom user model manager
        user = User.objects.create_user(first_name=fn, last_name=ln, email=email, username=username, password=password)

        return redirect('home')

def Signout(request):
    Cart.objects.filter(user=request.user).delete()
    logout(request)
    return redirect('home')



def cartbox(request):
    cart_items = Cart.objects.filter(user=request.user)

    return render(request, 'app/cartbox.html', {'cart_items': cart_items})



@login_required(login_url="/login")
def delete(request, id):
    try:
        add_to_cart = get_object_or_404(Cart, id=id)
    
    # Update session quantity by subtracting the quantity of the deleted item
        request.session['quantity'] = max(0, request.session.get('quantity', 0) - add_to_cart.quantity)
    
        add_to_cart.delete()
    except:
        return render(request,'app/error.html',{'msg':'Items does not exits'})
    
    return redirect('cartbox')




def edit(request, id):
    cart = Cart.objects.get(id=id)

    if request.method == 'POST':
        new_quantity = request.POST.get('quantity')

        # Validate that the new quantity is a positive integer
        if not new_quantity.isdigit() or int(new_quantity) <= 0:
            error_message = "Please enter a valid positive quantity."
            return render(request, 'app/edit.html', {'cart': cart, 'error_message': error_message})

        # Update the cart quantity and save
        cart.quantity = int(new_quantity)
        cart.save()

        return redirect('cartbox')

    return render(request, 'app/edit.html', {'cart': cart})
    
    




def order(request):
    user_cart = Cart.objects.filter(user=request.user)

    # Create an order for each item in the cart
    orders = []
    for cart_item in user_cart:
        order = Order.objects.create(
            user=request.user,
            cart=cart_item,
            product=cart_item.product_id,  # Access the product through the Cart model
        )
        orders.append(order)

        # Optionally, you can update the inventory or perform other actions

    # Clear the user's cart after creating orders
    user_cart.delete()

    # Calculate the total price for all orders
    total_price = sum(order.total_price() for order in orders)

    return render(request, 'app/order.html', {'orders': orders, 'total_price': total_price})

templates/app/add.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}Add{% endblock title %}

{% block content %}
hii i am add
{% load cart %}
<style>
   .product {
      display: inline-block;
      margin: 10px;
      text-align: center;
   }
</style>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
   $(document).ready(function () {
      $(".quantity-change").click(function () {
         var inputElement = $(this).siblings("input[type='number']");
         var currentValue = parseInt(inputElement.val());
         var changeAmount = parseInt($(this).data("change"));
         var newValue = currentValue + changeAmount;
         if (newValue >= 1) {
            inputElement.val(newValue);
         }
      });
   });
</script>

<div class="container">
   <div class="row">
      {% for product in products %}
      <div class="product">
         <img src="{{ product.product_image.url }}">
         <h6><strong>{{ product.product_name }} - {{ product.product_price }}</strong></h6>

         <div class="card-footer p-0 row no-gutters" id="{{ product.product_id }}">
            <form method="post" action="{% url 'add_to_cart' product_id=product.id %}">
               {% csrf_token %}
               <label for="quantity">Quantity:</label>
               <div class="quantity-controls">
                  <button type="button" class="quantity-change" data-change="-">-</button>
                  <input type="number" name="quantity" id="quantity" value="1" min="1" required>
                  <button type="button" class="quantity-change" data-change="+">+</button>
               </div>
               <input type="submit" value="Add">
            </form>
         </div>

      </div>
      {% endfor %}
   </div>
</div>
{% endblock content %}

templates/app/cartbox.html
{% extends 'base/base.html' %}

{% block content %}
  <h2>Your Cart</h2>
  {% if cart_items %}
    <div id="cartTableContainer" style="text-align: center;">
      <table id="cartTable" style="border-collapse: collapse; width: 80%; margin: auto;">
        <thead>
          <tr>
            <th style="border: 1px solid #ddd; padding: 8px;">Product</th>
            <th style="border: 1px solid #ddd; padding: 8px;">Quantity</th>
            <th style="border: 1px solid #ddd; padding: 8px;">Price</th>
            <th style="border: 1px solid #ddd; padding: 8px;">Image</th>
            <th style="border: 1px solid #ddd; padding: 8px;">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for cart_item in cart_items %}
            <tr>
              <td style="border: 1px solid #ddd; padding: 8px;">{{ cart_item.product_id.product_name }}</td>
              <td style="border: 1px solid #ddd; padding: 8px;">{{ cart_item.quantity }}</td>
              <td style="border: 1px solid #ddd; padding: 8px;">{{ cart_item.product_id.product_price }}</td>
              <td style="border: 1px solid #ddd; padding: 8px;"><img src="{{ cart_item.product_id.product_image.url }}" alt="{{ cart_item.product_id.product_name }} Image" style="max-width: 100px;"></td>
              <td style="border: 1px solid #ddd; padding: 8px;">
                <a href="{% url 'edit' id=cart_item.id %}" class="btn btn-info">Edit</a>
                <a href="{% url 'delete' id=cart_item.id %}" class="btn btn-danger">Delete</a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div style="text-align: center; margin-top: 20px;">
      <button id="orderButton" class="btn btn-success">Order</button>
    </div>

    <script>
      // You can add JavaScript functions or events here
      document.getElementById('orderButton').addEventListener('click', function() {
        window.location.href = "{% url 'order' %}";
      });
    </script>

  {% else %}
    <p>Your cart is empty.</p>
  {% endif %}
 
{% endblock %}

templates/app/edit.html
<!-- edit.html -->
{% extends 'base/base.html' %}

{% block content %}
    <h2>Edit Cart Item</h2>
    <form method="post">
        {% csrf_token %}
        
        <label for="id_quantity">Quantity:</label>
        <input type="number" name="quantity" id="id_quantity" value="{{ cart.quantity }}" min="1" required>
        
        <img src="{{ cart.product_id.product_image.url }}" alt="{{ cart.product_id.product_name }} Image" style="max-width: 100px;">
        
        <button type="submit">Update</button>
    </form>

    {% if error_message %}
        <p class="error">{{ error_message }}</p>
    {% endif %}
{% endblock %}

templates/app/error.html
{% extends 'core/base.html' %}
{% block title %} Error{% endblock title %}

{% block content %} 
<h1 style="text-align: center; color:red">{{msg}}</h1>
{% endblock content %}

templates/app/home.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}
{% load cart %}
<style>
   .product {
      display: inline-block;
      margin: 10px;
      text-align: center;
   }
</style>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
   $(document).ready(function () {
      $(".quantity-change").click(function () {
         var inputElement = $(this).siblings("input[type='number']");
         var currentValue = parseInt(inputElement.val());
         var changeAmount = parseInt($(this).data("change"));
         var newValue = currentValue + changeAmount;
         if (newValue >= 1) {
            inputElement.val(newValue);
         }
      });
   });
</script>

<div class="container">
   <div class="row">
      {% for product in products %}
      <div class="product">
         <div class="product-item" style="display: inline-block; vertical-align: top; margin-right: 100px;">
             <img src="{{ product.product_image.url }}" style="width: 400px; height: 400px; object-fit: cover;">
         </div>
         <h6><strong>{{ product.product_name }} - {{ product.product_price }}</strong></h6>
         <div class="card-footer p-0 row no-gutters" id="{{ product.product_id }}">
            {% if user.is_authenticated %}
               <form method="post" action="{% url 'add_to_cart' product_id=product.id %}">
                  {% csrf_token %}
                  <label for="quantity">Quantity:</label>
                  <div class="quantity-controls">
                     <input type="number" name="quantity" id="quantity" value="1" min="1" required>
                  </div>
                  <input type="hidden" name="next" value="{% url 'home' %}">
                  <input type="submit" value="Add to Cart">
               </form>
            {% else %}
            <style>
               .add-to-cart-button {
                  margin-right: 5px;
                  display: block;
                  margin: auto;
                  text-align: center;
               }
            
               .add-to-cart-button a {
                  color: #007bff; /* Set the color to blue */
                  border-color: #007bff; /* Set the border color to blue */
               }
            
               .add-to-cart-button a:hover {
                  background-color: #007bff; /* Change the background color on hover to blue */
                  color: #ffffff; /* Change the text color on hover to white */
               }
            </style>
            
            <div class="add-to-cart-button">
               <a class="btn btn-outline-success my-2 my-sm-0" href="{% url 'login' %}">Add to Cart</a>
            </div>
            
            {% endif %}
         </div>
      </div>
      {% endfor %}
   </div>
</div>
{% endblock content %}

templates/app/login.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}Login{% endblock title %}

{% block content %}
<div class="container">
    <form id="loginForm" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" class="form-control" id="username" name="username" required>
            <div class="invalid-feedback">Please enter your username.</div>
        </div>

        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control" id="password" name="password" required>
            <div class="invalid-feedback">Please enter your password.</div>
        </div>

        <button type="submit" class="btn btn-primary">Login</button>
    </form>

    <p class="mt-3">
        Don't have an account? <a href="{% url 'register' %}">Register here</a>.
    </p>
</div>

<script>
    // Add client-side validation using JavaScript
    document.getElementById('loginForm').addEventListener('submit', function (event) {
        var usernameInput = document.getElementById('username');
        var passwordInput = document.getElementById('password');

        if (!usernameInput.checkValidity()) {
            event.preventDefault();
            usernameInput.classList.add('is-invalid');
        }

        if (!passwordInput.checkValidity()) {
            event.preventDefault();
            passwordInput.classList.add('is-invalid');
        }
    });

    // Remove 'is-invalid' class on input focus
    document.querySelectorAll('.form-control').forEach(function (input) {
        input.addEventListener('focus', function () {
            this.classList.remove('is-invalid');
        });
    });
</script>
{% endblock content %}

templates/app/order.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}Order Confirmation{% endblock title %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Order Confirmation</h1>

    {% if orders %}
        <div class="row">
            <div class="col-md-6">
                <strong>Customer Name:</strong> {{ request.user.username }}
            </div>
            <div class="col-md-6">
                <div class="card border-success mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Total Order Price</h5>
                        <p class="card-text">{{ total_price }}</p>
                    </div>
                </div>
            </div>
        </div>

        <hr>

        <table class="table mt-3">
            <thead>
                <tr>
                    <th>Food Name</th>
                    <th>Total Quantity</th>
                   
                    <th>Food Price</th>
                    <th>Total Price</th>
                </tr>
            </thead>
            <tbody>
                {% for order in orders %}
                    <tr>
                        <td>{{ order.product.product_name }}</td>
                        <td>{{ order.cart.quantity }}</td>
                        
                        <td>{{ order.product.product_price }}</td>
                        <td>{{ order.total_price }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div style="text-align: center; margin-top: 20px;">
            <a id="orderButton" class="btn btn-success" onclick="finishOrder()" href="{% url 'home' %}">Finish</a>
          </div>
      
          <script>
            function finishOrder() {
              // Add logic to send order, if needed
              // For demonstration purposes, show a message for 3 seconds
              alert('Your order has been sent!');
              setTimeout(function() {
                // Redirect to the home page after 3 seconds
                window.location.href = "{% url 'home' %}";
              }, 3000);
            }
          </script>
    {% else %}
        <p class="mt-3">No orders were created.</p>
    {% endif %}

    <div class="mt-4">
        <p>Thank you for your purchase!</p>
    </div>
</div>

{% endblock %}

templates/app/register.html
{% extends "base/base.html" %}
{% load static %}

{% block title %}Register{% endblock title %}

{% block content %}
<div class="container">
    <form id="registerForm" method="POST">
        {% csrf_token %}
        
        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="firstname" class="form-label">First name</label>
                <input type="text" class="form-control" id="firstname" name="firstname" required>
            </div>
            <div class="col-md-6 mb-3">
                <label for="lastname" class="form-label">Last name</label>
                <input type="text" class="form-control" id="lastname" name="lastname" required>
            </div>
        </div>

        <div class="mb-3">
            <label for="address" class="form-label">Address</label>
            <input type="text" class="form-control" id="address" name="address" required>
        </div>

        <div class="mb-3">
            <label for="contact_no" class="form-label">Contact Number</label>
            <input type="text" class="form-control" id="contact_no" name="contact_no" required>
        </div>

        <div class="mb-3">
            <label for="email" class="form-label">Email address</label>
            <input type="email" class="form-control" id="email" name="email" required>
        </div>

        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" class="form-control" id="username" name="username" required>
        </div>

        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control" id="password" name="password" required>
        </div>

        <button type="submit" class="btn btn-primary">Register</button>
    </form>
</div>

<script>
    document.getElementById('registerForm').addEventListener('submit', function (event) {
        var requiredInputs = document.querySelectorAll('[required]');

        for (var i = 0; i < requiredInputs.length; i++) {
            var input = requiredInputs[i];

            if (!input.checkValidity()) {
                event.preventDefault();
                input.classList.add('is-invalid');
            }
        }
    });

    document.querySelectorAll('.form-control').forEach(function (input) {
        input.addEventListener('focus', function () {
            this.classList.remove('is-invalid');
        });
    });
</script>

{% endblock content %}

templates/base/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title></title>
    <link rel="stylesheet" href="css\styles.css">
  </head>
  {% include "base/navbar.html" %}
  <body>
    {% block content %}{% endblock content %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'home' %}">Ecommerce</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        
      </ul>
      <a style="margin-right:5px;" class="btn btn-outline-success my-2 my-sm-0" href="{% url 'cartbox' %}">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bag" viewBox="0 0 16 16">
            <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1m3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1z"></path>
        </svg>
        Cart {{ request.session.total_quantity|default:0 }}
    </a>
  
      {% if user.is_authenticated %}
      
    
      <a style="margin-right:5px;" class="btn btn-outline-success my-2 my-sm-0" href="{% url 'logout' %}" >Logout</a>
      {% else %}
      
      <a style="margin-right:5px;" class="btn btn-outline-success my-2 my-sm-0" href="{% url 'login' %}" >Login</a>
      <a style="margin-right:5px;" class="btn btn-outline-success my-2 my-sm-0" href="{% url 'register' %}">Register</a>
      
      
      
      {% endif %}
    </div>
  </nav>